FROM apache/airflow:latest

USER root

RUN apt-get update && \
    apt-get -y install git && \
    apt-get clean

USER airflow

RUN pip install --no-cache-dir \
    dbt-core==1.11.11 \
    dbt-snowflake==1.11.5