version: '3'

services:
  sleek-airflow:
    image: azurepipelineproject:latest 

    volumes:
      - ./airflow:/opt/airflow
      - ./python:/opt/project/python
      - ./data:/opt/project/data
      - ./snowflake_sql:/opt/project/snowflake_sql
      - ../Flights_dbt_proj:/opt/project/Flights_dbt_proj
      - ../dbt_profiles:/home/airflow/.dbt

    ports:
      - "8080:8080"

    command: airflow standalone

    environment:
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}